apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: celery-data
  name: celery-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
status: {}
