FROM docker/compose

WORKDIR /opt

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY docker-compose.yml /opt/app/
COPY docker-compose.build.yml /opt/app/
COPY docker-compose.prod.yml /opt/app/
COPY docker-compose.prod.selfhost.yml /opt/app/

CMD docker-compose -f docker-compose.yml -f docker-compose.build.yml -f docker-compose.prod.yml -f docker-compose.prod.selfhost.yml up