apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert -f docker-compose.yml -f docker-compose.build.yml -f docker-compose.prod.yml -f docker-compose.prod.selfhost.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  containers:
    - image: jeffreyca/spleeter-web-frontend:latest
      name: frontend
      ports:
        - containerPort: 80
      resources: {}
      volumeMounts:
        - mountPath: /webapp/frontend/assets
          name: assets
  restartPolicy: Never
  volumes:
    - name: assets
      persistentVolumeClaim:
        claimName: assets
status: {}
