apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert -f docker-compose.https.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/local/bin/kompose convert -f docker-compose.https.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - env:
            - name: API_HOST
              value: api
            - name: ENABLE_HTTPS
              value: "1"
            - name: UPLOAD_FILE_SIZE_LIMIT
              value: "100"
          image: nginx
          name: nginx
          resources: {}
          volumeMounts:
            - mountPath: /etc/letsencrypt
              name: nginx-claim0
      restartPolicy: Always
      volumes:
        - name: nginx-claim0
          persistentVolumeClaim:
            claimName: nginx-claim0
status: {}
