apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pretrained-models
  name: pretrained-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
status: {}
