apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: staticfiles
  name: staticfiles
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
