services:
  nginx:
    volumes:
      - /home/palm0101_book/audio-splitter/media:/webapp/media
  api:
    volumes:
      - /home/palm0101_book/audio-splitter/media:/webapp/media
  celery-fast:
    volumes:
      - /home/palm0101_book/audio-splitter/media:/webapp/media
  celery-slow:
    volumes:
      - /home/palm0101_book/audio-splitter/media:/webapp/media
